# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dmswebapi

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore DMS.Auth.sln

      - name: Build
        run: dotnet build DMS.Auth.sln --no-restore

      - name: Test
        run: dotnet test DMS.Auth.sln --no-build --verbosity normal

      - name: Build and Push Docker Image
        if: github.event_name == 'push'
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: kapildev244/dmswebapi
          registry: docker.io
          dockerfile: DMS.Auth/Dockerfile
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          tags: |
            latest
            main-${{ github.sha }}
