# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # - name: List repository files
    #   run: |
    #     pwd
    #     ls
    #     ls -R
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore
      run: dotnet restore DMS.Auth/DMS.Auth/DMS.Auth.csproj
    
    - name: Build
      run: dotnet build DMS.Auth/DMS.Auth/DMS.Auth.csproj --no-restore
    
    - name: Test
      run: dotnet test DMS.Auth/DMS.Auth/DMS.Auth.csproj --no-build --verbosity normal

    - name: Build and push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: kapildev244/dmswebapi
        registry: docker.io
        dockerfile: DMS.Auth/DMS.Auth//Dockerfile
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        tags: latest, master-${{ github.sha }}
 
    # - name: Trigger Render Deploy
    #   run: |
    #     curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

